FROM sleeps.cr.cloud.ru/dev-containers/building/go_app_builder AS builder

WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-s -w" -o /go/bin/app ./cmd/app/main.go
RUN upx -9 /go/bin/app

FROM alpine:latest AS runner

COPY --from=builder /go/bin/app ./

EXPOSE 8080

CMD ["./app"]